# install extension REST Client and click 'Send Request'

GET http://localhost:4000/auth

###
POST http://localhost:4000/auth
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}